apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: test-n
  replicas: 2
  template:
    metadata:
      labels:
        app: test-n
    spec:
      containers:
      - name: my-imag
        image: public.ecr.aws/y0j0v8z3/test-ecr:feature
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
  app: test-n
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036
