apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: nodejs-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: node-app
        image: public.ecr.aws/y0j0v8z3/test-ecr:feature
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32140
    protocol: TCP
